add_newline = false
# A minimal left prompt
format = """ $directory$character"""
palette = "catppuccin_mocha"
# move the rest of the prompt to the right
right_format = """$sudo$git_branch$git_state"""
command_timeout = 1000

[git_branch]
symbol = '🌱 '
format = '[ $symbol $branch ](bold teal)'

[git_state]
disabled = false
format = '[\($state( $progress_current of $progress_total)\)]($style) '

[git_status]
disabled = false

[sudo]
format = '🔒'
disabled = false

[directory]
truncation_length = 6
truncation_symbol = '…/'
style = 'bold sapphire'

[character]
#success_symbol = '[](bold red)'
success_symbol = '[](bold red)'

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
